# Generated by Django 5.2.3 on 2025-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_candidature", models.DateTimeField(auto_now_add=True)),
                ("lettre_motivation", models.TextField()),
                (
                    "statut_candidature",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "en attente"),
                            ("ACCEPTEE", "acceptée"),
                            ("REFUSEE", "refusée"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OffreEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("type_contrat", models.CharField(max_length=100)),
                ("localisation", models.CharField(max_length=255)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
