# Generated by Django 5.2.3 on 2025-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidature",
            name="statut_candidature",
        ),
        migrations.AddField(
            model_name="candidature",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "en attente"),
                    ("acceptée", "acceptée"),
                    ("refusée", "refusée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="lettre_motivation",
            field=models.TextField(blank=True),
        ),
    ]
