# Generated by Django 5.2.3 on 2025-06-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profildiplome",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="formationexperience",
            name="profil_diplome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profildiplome"
            ),
        ),
        migrations.AddField(
            model_name="competence",
            name="profil_diplome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profildiplome"
            ),
        ),
    ]
